---

  - name: instalando o pacote rsyslog-ng
    apt:
      name: syslog-ng
      state: present
    with_items:
         - "{{ nos_master_auditoria }}"
   # when: ansible_hostname in item.name

  - debug:
      msg: "{{ nos_master_auditoria }}"
