---
# handlers file for docker_registry

  - name: reiniciar syslog-ng
    systemd:
        name: syslog-ng
        daemon_reload: yes
        state: restarted
        enabled: yes

  - name: reiniciar rsyslog
    systemd:
         name: rsyslog
         daemon_reload: yes
         state: restarted
         enabled: yes
